name: pull-request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run eslint check
        uses: sibiraj-s/action-eslint@v3
        with:
          all-files: true
          ignore-path: .eslintignore
          ignore-patterns: |
            dist/
            lib/
